# Generated by Django 5.2.6 on 2026-02-10 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_db', '0006_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='product',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='user',
        ),
        migrations.AddField(
            model_name='transaction',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='productName',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
