# Generated by Django 5.2.6 on 2026-02-10 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_db', '0008_transaction_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='price',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='productName',
        ),
        migrations.AddField(
            model_name='transaction',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users_db.product'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='total_price',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_date',
            field=models.DateTimeField(),
        ),
    ]
